---
title: "Risultati SPDE"
author:
  - name: Guido Fioravanti
    affiliation: ISPRA
date: 02-19-2021
params:
  regione: lombardia
  inquinante: no2
output:
  distill::distill_article:
    self_contained: false
---

```{r intro,include=FALSE,echo=FALSE,warning=FALSE}
library("tidyverse")
library("janitor")
library("INLA")
library("brinla")
library("sf")
library("cowplot")
library("knitr")
library("skimr")
library("raster")
library("sp")
library("rpulvinla")
library("downloadthis")
library("ggspatial")
library("guido")
library("scico")
library("regioniItalia")

st_union(lombardia,piemonte)->shapeRegione
st_union(shapeRegione,veneto)->shapeRegione
st_union(shapeRegione,emiliaromagna)->shapeRegione
st_union(shapeRegione,toscana)->shapeRegione
st_union(shapeRegione,valleaosta)->shapeRegione
st_union(shapeRegione,trentino)->shapeRegione
st_union(shapeRegione,friuliveneziagiulia)->shapeRegione

knitr::opts_chunk$set(layout="l-body-outset",warning = FALSE,message = FALSE,echo=FALSE,fig.height=4,include = FALSE,eval = TRUE)
set.seed(1)
creaCalendario(annoI=2019,annoF=2020)->calendario

calendario %>%
  mutate(date=as.Date(glue::glue("{yy}-{mm}-{dd}"))) %>%
  filter(date >= as.Date("2019-01-02") & date<= as.Date("2020-05-03"))->calendario

```

# `r params$inquinante`  


```{r leggiRisultati}
#MESE<-3
readRDS(glue::glue("dati{MESE}_{params$regione}.RDS"))->dati
25->n_giorni

if(!exists("inla.out")) {readRDS(glue::glue("result{MESE}_{params$regione}.RDS"))->inla.out}
readRDS(glue::glue("iset{MESE}_{params$regione}.RDS"))->iset
readRDS(glue::glue("stack.training{MESE}_{params$regione}.RDS"))->mystack
try({readRDS(glue::glue("spde{MESE}_{params$regione}.RDS"))->spde})
readRDS(glue::glue("mesh{MESE}_{params$regione}.RDS"))->mesh
```


```{r myformula,include=TRUE}
as.formula(inla.out$.args$formula)->myformula
```

### Formula

`r as.character(myformula)`

---


```{r spde,include=TRUE,include=FALSE}
inla.spde.result(inla.out,name="i",spde=spde,do.transform=TRUE)->spdeResults
```

Range (mean value): `r try({round(exp(spdeResults$summary.log.range.nominal$mean),0)})` km

```{r,fig.width=8,fig.height=4,include=TRUE}
par(mfrow=c(1,2))
spdeResults$marginals.range.nominal[[1]][,1]->X
spdeResults$marginals.range.nominal[[1]][,2]->Y  
plot(X,Y,type="l",main="Range spde",xlim=c(50,200))
spdeResults$marginals.variance.nominal[[1]][,1]->XX
spdeResults$marginals.variance.nominal[[1]][,2]->YY
plot(XX,YY,type="l",main="Varianza spde",xlim=c(0,20))
```

### Latent field

```{r graficoLatentField,include=TRUE,fig.width=5,fig.asp=0.8}
in_km(shapeRegione)->shapeRegione
st_crs(shapeRegione)->crsKM
st_bbox(shapeRegione)->estensione
as_Spatial(shapeRegione)->sp_shapeRegione


purrr::map(1:n_giorni,.f=function(BB){
  

  BB->giorno
      
  inla.out$summary.random$i[iset$i.group==BB,"mean"]->campo #
  inla.mesh.projector(mesh,xlim=c(estensione["xmin"],estensione["xmax"]),ylim=c(estensione["ymin"],estensione["ymax"]),dims = c(250,250))->myproj
  inla.mesh.project(myproj,campo)->campoProj
  raster(list(x=myproj$x,y=myproj$y,z=campoProj))->myraster
  myraster-0.021905900->myraster
  (exp(myraster)-1)->raster
  
  myraster[myraster>0.8]<-0.8
  myraster[myraster< -0.8]<- -0.8
  #exp(myraster)->myraster
  crs(myraster)<-crsKM

  mask(myraster,sp_shapeRegione)->myraster
  
  ggplot()+
    ggspatial::layer_spatial(data=myraster)+
    #geom_sf(data=shapeRegione)+
    scale_fill_scico(palette="vik",na.value="transparent",limits=c(-0.8,0.8))+
    ylab(BB)->grafico
  print(grafico)
  # plot(myraster)
  # plot(mesh,add=TRUE,lwd=0.5)
  # plot(st_geometry(shapeRegione),add=TRUE,lwd=2)

  myraster
  
})->listaRaster

stack(listaRaster)->mystack
#writeRaster(mystack,"mystack.tif")
```

