---
title: Lombardia NO2, mappe giorni festivi
output: html_document
---

```{r,include=FALSE,echo=FALSE,warning=FALSE,message=FALSE}
library("tidyverse")
library("scico")
library("raster")
library("regioniItalia")
library("patchwork")
library("sf")
library("ggnewscale")
library("bfastSpatial")
library("osmdata")
library("ggspatial")
library("stazioniMonitoraggio")

knitr::opts_chunk$set(include=FALSE,warning=FALSE,message=FALSE,echo=FALSE)

# getbb("Lombardia") %>% opq(timeout=25*100) %>% add_osm_feature(key="highway",value=c("motorway")) %>% osmdata_sf()->strade
# strade$osm_lines->strade
# st_crs(strade)<-4326
# st_transform(strade,crs=32632)->strade
# st_intersection(strade,lombardia)->strade
# saveRDS(strade,"strade.RDS")

#readRDS("strade.RDS")->strade
st_as_sf(stazioni,coords=c("st_x","st_y"),crs=4326)->sfStazioni
st_transform(sfStazioni,crs=32632)->sfStazioni
sfStazioni %>%
  filter(regione=="LOMBARDIA" & no2=="completa 2016-2020")->sfStazioni


TIPO<-c("feriali","festivi")[2]
SOGLIA<-0.3
list.files(pattern = glue::glue("^mediaMasked_{TIPO}_.+nc"),full.names = TRUE,include.dirs = TRUE,recursive = TRUE)->ffile
#ffile[grepl("20",ffile)]->ffile


raster("i_surface.tif")->i_surface
mask(i_surface,lombardia)->i_surface
crop(i_surface,lombardia)->i_surface

st_read("Limiti01012021_g/ProvCM01012021_g/","ProvCM01012021_g_WGS84") %>%
  filter(COD_REG==3) %>%
  mutate(zona_rossa=ifelse(DEN_PROV=="Lodi" | DEN_PROV=="Padova",1,NA))->province

filtra<-function(mylayer,soglia=0,nome=NULL,inverti=FALSE){
  
  if(!inverti){
    mylayer[mylayer<soglia & mylayer>0]<-NA
    mylayer[mylayer > -soglia & mylayer<0]<- NA
  }else{
    mylayer[mylayer> soglia]<-999
    mylayer[mylayer < -soglia]<- 999   
    mylayer[mylayer!=999]<-NA
  }
  
  mylayer[mylayer>1]<-1
  mylayer[mylayer< -1]<- -1  
  

  #areaSieve(mylayer,thresh = 5000,cores=8)->mylayer
  names(mylayer)<-nome
  
  mylayer
  
}

purrr::map(paste0("mese",1:4),.f=function(nomeMese){
  
  #if(nomeMese!="mese4") return()
  ffile[grepl(nomeMese,ffile)]->fileMese

  purrr::map(fileMese,.f=~brick(.))->listaBricks
  
  purrr::map_int(listaBricks,.f=nlayers)->numeroLayers
  unique(numeroLayers)->unici
  
  if(length(unici)!=1){
    which.max(numeroLayers)->qualeBrick
    listaBricks[[qualeBrick]]<-subset(listaBricks[[qualeBrick]],2:max(numeroLayers))
    
  }

  
  purrr::map(1:min(unici),.f=function(ll){
    
    listaBricks[[1]][[ll]]->mascherato0 #18 vs 19

    listaBricks[[2]][[ll]]->mascherato1
    listaBricks[[3]][[ll]]->mascherato2

    filtra(mascherato0,soglia=SOGLIA,nome=nomeMese,inverti = TRUE)->mascherato0
    filtra(mascherato1,soglia=SOGLIA,nome=nomeMese)->mascherato1
    filtra(mascherato2,soglia=SOGLIA,nome=nomeMese)->mascherato2
    
    #prodotto mi permette di individuare le aree comuni al 1820 e 1920 dove le medie
    #sono statisticamente significative
    mascherato1*mascherato2->prodotto
    #dove prodotto e' <0 significa che una media aveva un segno e l'altra media aveva
    #il segno opposto..vogliamo evidenziare solo le zone con medie statisticamente
    #significative in entrambi i casi e con segno della media uguale
    prodotto[prodotto<0]<-NA
    #elimino le aree della maschera con clump troppo piccoli
    areaSieve(prodotto,thresh = 5000,cores=8)->prodotto

    mask(mascherato1,prodotto)->mascherato1
    mask(mascherato2,prodotto)->mascherato2
    
    #mascherato0 sono i valori della media sul periodo 2018 e 2019... vogliamo
    #eliminare da mascherato1 e mascherato2 eventuali segnali statisticamente
    #significativi presenti nelle stesse aree durante il periodo 2018 e 2019...
    #Ilsegnale che vogliamo trovare non deve presentarsi anche nel confronto 2018 
    #vs 2019
    mascherato0*mascherato1->mascherato01
    #mascherato01 e' l'area comune a mascherato0 e mascherato1, imponiamo
    #che il segno della media nelle due mappe sia lo stesso
    mascherato01[mascherato01<0]<-NA
    #elimino eventuali aree troppo piccole
    areaSieve(mascherato01,thresh = 5000,cores=8)->mascherato01

    mascherato0*mascherato2->mascherato02
    mascherato02[mascherato02<0]<-NA
    areaSieve(mascherato02,thresh = 5000,cores=8)->mascherato02

    #inverse=TRUE..manteniamo le aree con NA ed eliminiamo quelle non NA..cioe'
    #eliminiamo da mascherato1 e mascherato2 zone in cui anche nel confronto 18 vs 19
    #si presenta un segnale significativo con lo stesso segno di mascherato1/mascherato2
    mask(mascherato1,mask=mascherato01,inverse=TRUE)->mascherato1
    mask(mascherato2,mask=mascherato02,inverse=TRUE)->mascherato2
        
    list(anno1820=mascherato1,anno1920=mascherato2)
    
  })->listaFileMascherati
  
  
  purrr::map(listaFileMascherati,"anno1820") %>% brick->brick1820
  purrr::map(listaFileMascherati,"anno1920") %>% brick->brick1920
  
  list(anno1820=brick1820,anno1920=brick1920)

})->listaBrick

purrr::map(listaBrick,"anno1820") %>% brick->brick1820
purrr::map(listaBrick,"anno1920") %>% brick->brick1920

raster::nlayers(brick1820)->numeroLayers


grafico<-function(mybrick,anni,tipo){

  purrr::map(1:numeroLayers,.f=function(ll){

    names(mybrick[[ll]])->mese
    
    # if(grepl("1",mese)) mese<-"Gennaio"
    # if(grepl("2",mese)) mese<-"Febbraio"
    # if(grepl("3",mese)) mese<-"Marzo"
    # if(grepl("4",mese)) mese<-"Aprile"
   
    
    tabularaster::as_tibble(mybrick[[ll]],xy=TRUE)->df
  
    ggplot()+
      geom_sf(data=lombardia,fill="transparent")+
      layer_spatial(i_surface,aes(fill=stat(band1)),alpha=0.6)+
      scale_fill_scico(palette="grayC",na.value="transparent",guide=FALSE,direction=-1)+
      new_scale_fill()+
      #geom_sf(data=strade,color="orange",size=0.1)+
      geom_sf(data=province,aes(fill=as.character(zona_rossa)),size=0.1,color="#333333",alpha=0.3)+
      scale_fill_discrete(na.value="transparent",guide=FALSE)+
      new_scale_fill()+
      geom_tile(data=df,aes(x=x,y=y,fill=cellvalue),alpha=0.5)+
      scico::scale_fill_scico(palette="imola",limits=c(-1,1),na.value=NA,direction=1)+
      geom_sf(data=sfStazioni,pch=21,fill="firebrick",size=0.5)+
      ylab(mese)+
      theme_minimal()+
      theme(panel.grid = element_blank(),axis.title.x = element_blank(),axis.text = element_blank())
  
  })->listaGrafici

  purrr::reduce(listaGrafici[1:length(listaGrafici)],.f=`+`)+
        plot_layout(guides="collect",ncol = 4)+plot_annotation(title=anni,subtitle=tipo)

}
```

### Mappe 2018 vs 2020

```{r,fig.width=12,fig.height=18,include=TRUE}
grafico(brick1820,anni="2018 vs 2020",tipo=TIPO)->grafico1820
print(grafico1820)
```

### Mappe 2019 vs 2020

```{r,fig.width=12,fig.height=18,include=TRUE}
grafico(brick1920,anni="2019 vs 2020",tipo=TIPO)->grafico1920
print(grafico1920)
```