---
title: "Modello PM10 Lombardia, ar1 su spde serie gennaio-maggio 2020"
description: |
  Primo modello testato per progetto PULVIRUS (2020 vs 2019/2018).
author:
  - name: guidofioravanti
date: 03-03-2021
output:
  distill::distill_article:
    self_contained: false
---

Per il progetto PULVIRUS, il primo modello che si e' testato e' un modello analogo a quello descritto in [Cameletti (2020)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7365121/), aggiungendo la componente spaziale (spde con ar1).

Il modello prevede:

- variabili meteoclimatiche come effetti fissi

- il campo spde con `ar1` sul giorno

- un random effect (`iid`) sulle centraline

- un effetto lineare sul giorno (variabile `day`).


Questo modello sull'intero periodo [gennaio-maggio 2020](./2020/analisi-covariate.html) e' caratterizzato da:

- un range molto grande (213 km)

- un rho su spde pari a 0.94

Entrambi i valori sono decisamente troppo alti, soprattutto se confrontati con i risultati dello stesso modello per gli anni [2019](./2019/analisi-covariate.html) e [2018](./2018/analisi-covariate.html) .

Se per l'anno 2020 viene inserito un effetto non lineare sul giorno (rw1 su `say`) mantenendo un ar1 su spde si ottiene un campo spde con range e rho piu' bassi (si veda ad esempio [questo modello](https://progettopulvirus.github.io/pulvinla/posts/2021-03-03-pm10-lombardia-modello-con-pvalue-ar1-su-spde-rw1-su-day-e-stationeucode/)  che include anche la variabile `pvalue` ovveroo il valore del PM10 nel giorno precedente). 

**Il problema del rho molto alto su spde riguarda anche l'NO2 ma ne' l'uso dell'rw1 su `day` ne' l'uso del valore dell'inquinante nel giorno precedente risolve il problema.**   

Per il PM10 il problema sembra essere il periodo aprile-maggio:

- [risultati 2020](./aprile_maggio_2020/analisi-covariate.html): rho 0.52 e range 204 km 

- [risultati 2019](./aprile_maggio_2019/analisi-covariate.html): rho 0.41 e range 167 km

- [risultati 2018](./aprile_maggio_2018/analisi-covariate.html): rho 0.54 e range 155 km


Per il periodo gennaio-marzo:

- [risultati 2020](./gennaio_marzo_2020/analisi-covariate.html): rho 0.70 e range 124 km

- [risultati 2019](./gennaio_marzo_2019/analisi-covariate.html): rho 0.56 e range 131 km

- [risultati 2018](./gennaio_marzo_2018/analisi-covariate.html): rho 0.61 e range 151 km



