---
title: "Emissioni NO2 e PM10, Lombardia"
description: |
  Gennaio -maggio, serie 2016-2019 vs 2020.
author:
  - name: guidofioravanti
date: 03-01-2021
params:
  annoI: 2016
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
library("lombardia")
library("stazioniMonitoraggio")
library("tidyverse")
library("rpulvinla")
library("scico")
knitr::opts_chunk$set(echo = FALSE,layout="l-page",fig.width = 12,fig.height = 10)
theme_set(theme_bw()+theme(panel.grid = element_blank()))
```

Serie 2016 - 2019 (in blu)  e serie giornaliere del 2020 (rosa) per il periodo 1 Gennaio - 31 Maggio per tipo zona (U: Urban, S: Suburban, R: Rural).

### PM10

```{r pm10}
left_join(pm10,stazioni) %>%
  filter(yy %in% params$annoI:2020) %>%
  filter(mm %in% 1:5)->dati
purrr::map_dfr(params$annoI:2020,.f=function(.y){prepara_dati(.x=dati %>% filter(yy==.y))})->finale

finale %>%
  mutate(station_eu_code2=paste0(station_eu_code,yy)) %>%
  mutate(anno=ifelse(yy==2020,"2020","<2020"))->finale
```


```{r}
ggplot(data=finale)+
  geom_line(aes(x=banda,y=value,group=station_eu_code2,colour=anno,alpha=anno))+
  facet_wrap(~tipo_zona,nrow=3)+
  scale_color_scico_d(palette="berlin")+
  scale_alpha_discrete(range=c(0.25,0.8))
```

### NO2

```{r no2}
left_join(no2,stazioni) %>%
  filter(yy %in% params$annoI:2020) %>%
  filter(mm %in% 1:5)->dati
purrr::map_dfr(params$annoI:2020,.f=function(.y){prepara_dati(.x=dati %>% filter(yy==.y))})->finale

finale %>%
  mutate(station_eu_code2=paste0(station_eu_code,yy)) %>%
  mutate(anno=ifelse(yy==2020,"2020","<2020"))->finale
```


```{r}
ggplot(data=finale)+
  geom_line(aes(x=banda,y=value,group=station_eu_code2,colour=anno,alpha=anno))+
  facet_wrap(~tipo_zona,nrow=3)+
  scale_color_scico_d(palette="berlin")+
  scale_alpha_discrete(range=c(0.25,1))
```
