---
title: "Analisi PM10 Lombardia"
description: |
  Descrizione PM10, serie 2013-2020.
author:
  - name: Guido Fioravanti
    affiliation: ISPRA
date: 02-10-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE,echo=FALSE,message=FALSE,warning=FALSE}
library("tidyverse")
library("lombardia")
library("datiMeteo")
library("stazioniMonitoraggio")
library("regioniItalia")
library("sf")
library("scico")
library("ggspatial")
library("data.tree")
library("raster")
library("patchwork")

knitr::opts_chunk$set(include = TRUE,echo=FALSE,message = FALSE,warning = FALSE)

PARAMETRO<-c("pm10","no2")[1] 
assign("inquinante",eval(parse(text=PARAMETRO)))
#compare::compareIdentical(inquinante,no2)

#bug da correggere: alcune serie hanno record duplicati, eliminare righe con pollutant_fk==NA
inquinante %>%
  filter(!is.na(pollutant_fk))->inquinante

stopifnot(nrow(inquinante)!=0)

#codici stazioni dell'inquinante per tutta la regione: sono i codici delle stazioni che hanno dati (altrimenti non comparirebbero
#nel pacchetto R).
unique(inquinante$station_eu_code)->codiciStazioni

#load("brescia.rda")

left_join(inquinante,meteo,by=c("station_eu_code"="station_eu_code","date"="date"))->dati

#creo un oggetto spaziale
stazioni[,c("station_eu_code","nome_stazione","st_x","st_y","altitudine")]->puntiStazione
st_as_sf(puntiStazione ,coords = c("st_x","st_y"),crs=4326)->puntiStazione
st_transform(puntiStazione,crs = 32632)->puntiStazioneUTM

#stazioni che appartengono a "Area" (regione, provincia..)
lombardia->Area
st_intersection(puntiStazioneUTM,Area)->stazioniArea

#stazioni che appartengono ad Area e con dati in "inquinante"
stazioniArea[stazioniArea$station_eu_code %in% codiciStazioni,]->stazioniArea


#' quante stazioni
length(unique(stazioniArea$station_eu_code))

raster("_dem.tif")->dem
raster::crop(dem,Area)->demArea
```

```{r mappaAra}
theme_set(theme_bw()+theme(panel.grid.minor = element_blank(),
                           panel.grid.major.x = element_blank(),
                           axis.text.x.bottom =element_text(angle=90)))

ggplot()+
  ggspatial::layer_spatial(data=demArea)+
  ggspatial::geom_sf(data=Area,fill="transparent",colour="black")+
  geom_sf(data=stazioniArea,aes(fill=altitudine),pch=21)+
  scale_fill_scico(palette="bamako")
```

Numero stazioni: `r nrow(stazioniArea)`

```{r sintesi}
#selezioniamo dati con codici in "stazioniArea" (stazioni che cadono in Area e con dati)
#selezioniamo serie nel periodo gennaio-giugno
dati %>%
  filter(station_eu_code %in% stazioniArea$station_eu_code) %>%
  filter(mm %in% 1:6)->subDati

left_join(subDati,stazioniMonitoraggio::stazioni[,c("station_eu_code","nome_stazione","tipo_zona")]) %>%
  mutate(tipo_zona=as.factor(tipo_zona))->subDati
```

### Numero di osservazioni per anno per stazione

Tutte le serie coprono il periodo 2013-2020 (ad eccezione di una stazione).

```{r disponibilitaDatiSerie,fig.height=6}
ggplot(data=subDati)+
  geom_bar(aes(x=yy),fill="firebrick")+
  facet_wrap(~station_eu_code)
```

### Distibuzione `r PARAMETRO`

```{r skim1}
print(skimr::skim(subDati[,c("yy","mm","dd","value","tipo_zona")] ))
```

### Distibuzione `r PARAMETRO` per tipo di zona (Urban, Suburban, Rural)

```{r skim2}
print(skimr::skim(subDati %>% dplyr::select(value,tipo_zona) %>% group_by(tipo_zona)))
```

<br> 


```{r distribuzioneDati,fig.height=10}
ggplot(data=subDati)+
  geom_boxplot(aes(x=station_eu_code,y=value,fill=tipo_zona))+
  #geom_hline(yintercept = 50,colour="red")+
  facet_wrap(~tipo_zona,scales = "free_x",nrow = 3)
```


### Distribuzione mensile `r PARAMETRO`

```{r distribuzioneMensile,fig.height=10,fig.width=10}
subDati %>%
  mutate(banda=lubridate::yday(date))->subDati

ggplot(data=subDati)+
  geom_boxplot(aes(x=as.character(mm),y=value,fill=tipo_zona))+
  facet_wrap(~tipo_zona,scales = "free_x",nrow = 3)+
  scale_x_discrete(labels=month.abb[1:6])+
  ylab(PARAMETRO)->grafico1

ggplot(data=subDati)+
  geom_point(aes(x=banda,y=value),alpha=0.25)+
  geom_smooth(method="lm",formula=y~x,se = FALSE,aes(x=banda,y=value))+
  facet_wrap(~tipo_zona,scales = "free_x",nrow = 3)+
  xlab("giorni")+
  ylab(PARAMETRO)->grafico2

grafico1+grafico2
```




