---
title: "Confronto meteo 2020 vs anni precedenti"
description: |
  Serie marzo-maggio.
author:
  - name: guidofioravanti
date: 03-03-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE,message = FALSE,warning = FALSE,echo=FALSE}
library("tidyverse")
library("datiMeteo")
library("lombardia")
library("patchwork")

knitr::opts_chunk$set(include = TRUE,message = FALSE,warning = FALSE,echo=FALSE,layout="l-page",fig.width = 12,fig.height = 8)

theme_set(theme_bw())

left_join(pm10,meteo, by = c("station_eu_code", "date"))->dati

dati %>% 
  mutate(dtr=tmax2m-tmin2m) %>%
  mutate(yy=as.character(yy)) %>%
  filter(mm %in% 1:5)->dati

boxplot_gennaio_maggio<-function(.x){ 
  
  purrr::map(.x,.f=function(nomeVar){ 
  
    which(names(dati)==nomeVar)->colonna
    stopifnot(length(colonna)==1)
    
    names(dati)[colonna]<-"var" 
    
    ggplot(data=dati,aes(x=yy,y=var))+
      geom_boxplot()+
      labs(title=glue::glue("Parametro: {nomeVar}, gennaio-maggio"))
  })->listaGrafici
  
  listaGrafici
  
}#fine funzione 

boxplot_marzo_maggio<-function(.x){ 

  purrr::map(VARIABILI,.f=function(nomeVar){ 
  
    which(names(dati)==nomeVar)->colonna
    stopifnot(length(colonna)==1)
  
    names(dati)[colonna]<-"var" 
  
    ggplot(data=dati %>% filter(mm %in% 3:5),aes(x=yy,y=var))+
      geom_boxplot()+
      facet_wrap(~mm,scales = "free",nrow=3)+
      labs(title=glue::glue("Parametro: {nomeVar}, marzo-maggio"))
  
  })->listaGraficiMensili

  listaGraficiMensili  
}
```

```{r}
c("t2m","tmax2m","tmin2m")->VARIABILI

#boxplot_gennaio_maggio(.x=VARIABILI)->listaGrafici
boxplot_marzo_maggio(.x=VARIABILI)->listaGraficiMensili

```

### Temperatura 

```{r,include=TRUE,eval=FALSE}
listaGrafici[[1]]+listaGrafici[[2]]+listaGrafici[[3]]
```


```{r,include=TRUE}
listaGraficiMensili[[1]]+listaGraficiMensili[[2]]+listaGraficiMensili[[3]]
```

### PBL

```{r}
c("pblmax","pblmin","pbl00","pbl12")->VARIABILI

#boxplot_gennaio_maggio(.x=VARIABILI)->listaGrafici
boxplot_marzo_maggio(.x=VARIABILI)->listaGraficiMensili
```


```{r,include=TRUE,eval=FALSE}
listaGrafici[[1]]+listaGrafici[[2]]+listaGrafici[[3]]+listaGrafici[[4]]
```


```{r,include=TRUE}
listaGraficiMensili[[1]]+listaGraficiMensili[[2]]+listaGraficiMensili[[3]]+listaGraficiMensili[[4]]
```

### Net Irradiance e DiurnalTemperature Range (DTR)

```{r}
c("nirradiance","dtr")->VARIABILI

boxplot_marzo_maggio(.x=VARIABILI)->listaGraficiMensili
```

```{r,include=TRUE}
listaGraficiMensili[[1]]+listaGraficiMensili[[2]]
```

### Relative Humidity e Total precipitation

```{r}
c("rh","tp")->VARIABILI

boxplot_marzo_maggio(.x=VARIABILI)->listaGraficiMensili
```

```{r,include=TRUE}
listaGraficiMensili[[1]]+listaGraficiMensili[[2]]
```
