---
title: NO2
output: html_document
params:
  mese: 3
---

Mese: `r month.name[params$mese]`

Media delle 1000 simulazioni con inla.posterior.sample

Cosa vogliamo verificare: l'effetto del meteo  sulla stima delle concentrazioni.

```{r setup, include=FALSE}
library("INLA")
library("tidyverse")
library("patchwork")

list.files(pattern=glue::glue("^samples[{params$mese}]_meteo.csv$"))->ffile
purrr::map_dfr(ffile,.f=vroom::vroom,delim=";",col_names = TRUE)->dati_meteo
dati_meteo$tipo<-"con_meteo"

list.files(pattern=glue::glue("^samples[{params$mese}].csv$"))->ffile
purrr::map_dfr(ffile,.f=vroom::vroom,delim=";",col_names = TRUE)->dati
dati$tipo<-"senza_meteo"

bind_rows(dati_meteo,dati)->dati
```


```{r,include=FALSE}
unique(dati$station_eu_code)->CODICI

purrr::map(CODICI,.f=function(codex){

  dati %>%
    filter(station_eu_code==codex)->subDati
  
  subDati %>%
    gather(key="sample",value="svalue",-value,-date,-banda,-yy,-mm,-dd,-station_eu_code,-tipo)->subDati
  
  subDati %>%
    mutate(sg=glue::glue("{tipo}_{sample}")) %>%
    mutate(sy=glue::glue("{yy}_{sample}")) %>%
    mutate(secy=glue::glue("{yy}_{station_eu_code}"))->subDati
  
   ggplot(data=subDati %>% filter(sample=="media"))+
     #geom_line(aes(x=banda,y=svalue,group=sy),alpha=0.1,color="lightgray")+
     ylab(codex)+
     geom_line(aes(x=banda,y=exp(svalue),group=sg,colour=tipo))+facet_wrap(~as.character(yy))+theme_bw()

})->listaGrafici
```


```{r,include=TRUE,fig.width=18,fig.height=80,echo=FALSE}
purrr::reduce(listaGrafici,.f=`+`)+plot_layout(ncol=3,guides="collect")
```
